version: '3'

services:
#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    env_file:
#      - db.env
    #environment:
    #    MYSQL_ROOT_PASSWORD: mypw
    #    MYSQL_DATABASE: mydb
    #    MYSQL_USER: myapp_user
    #    MYSQL_PASSWORD: myapp_passwd
    #    MYSQL_ALLOW_EMPTY_PASSWORD: no
  web:
    build:
      dockerfile: Dockerfile
#      platform: linux/amd64
    command: python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
#    env_file:
#      - db.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
#    depends_on:
#      - db
    extra_hosts:
        - "host.docker.internal:host-gateway"
    network_mode: bridge