# Generated by Django 3.2.16 on 2023-03-26 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('resource_type', models.CharField(default='single', max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('task_id', models.CharField(max_length=50)),
            ],
        ),
    ]
