# Generated by Django 3.2.16 on 2023-03-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
