# Generated by Django 3.2.16 on 2023-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportal', '0002_auto_20230327_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
