# Generated by Django 3.2.16 on 2023-05-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportal', '0003_resource_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='publication_name',
            field=models.CharField(default='resource_name_default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='task_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
