# Generated by Django 3.2.24 on 2024-02-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportal', '0006_auto_20231120_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
